spring.data.mongodb.uri=mongodb+srv://santiagoaceroo:FSjoc7rwYTgjgsS0@unieventobd.1lsdh.mongodb.net/Proyecto?retryWrites=true&w=majority&appName=unieventoBD
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

